### PR TITLE
Ignore composables that emit content in their own window.

### LINKED ISSUE #109: modifier-missing-check: Wrong report for fake content emitters
Currently, the `modifier-missing-check` rule shows an error for things that are technically content emitters but don't emit real content in terms that the content is a different window.

In the following example it does not really make sense to supply a modifier because the composable is really encapsulating it's contents.
```kotlin
@Composable
public fun MyDialog() {
  AlertDialog(
    onDismissRequest = { /*TODO*/ },
    buttons = { Text(text = "Button") },
    text = { Text(text = "Body") },
  )
}
```

The same applies for composables like `ModalBottomSheetLayout`.

One solution could be be to extend the current rule logic and check if the function has a single direct content emitter which is one of these window-style content emitters.

Tested with 0.0.22

### PR DESCRIPTION
**Pull request by PaulWoitaschek**
Fixes #109

### CODE REVIEW

File: core-common/src/main/kotlin/com/twitter/rules/core/util/Composables.kt [hunk 1]
```diff
@@ -28,6 +49,15 @@ private val KtCallExpression.containsComposablesWithModifiers: Boolean
         .filter { it.isNamed() }
         .any { it.getArgumentName()?.text == "modifier" }
 
+/**
+ * This is a denylist with common composables that emit content in their own window. Feel free to add more elements
```
Comment (kenyee) [inline core-common/src/main/kotlin/com/twitter/rules/core/util/Composables.kt:53]: probably don't need the feel free sentence in the comments.

File: core-common/src/main/kotlin/com/twitter/rules/core/util/PsiElements.kt [hunk 2]
```diff
@@ -5,28 +5,27 @@ package com.twitter.rules.core.util
...
 inline fun <reified T : PsiElement> PsiElement.findChildrenByClass(): Sequence<T> =
     sequence {
-        val klass = T::class
         val queue: Deque<PsiElement> = LinkedList()
         queue.add(this@findChildrenByClass)
         while (queue.isNotEmpty()) {
             val current = queue.pop()
-            if (klass.isInstance(current)) {
-                yield(current as T)
+            if (current is T) {
```
Comment (kenyee) [inline core-common/src/main/kotlin/com/twitter/rules/core/util/PsiElements.kt:17]: nice optimization 😄

**Review by kenyee — COMMENTED** [review]
one minor nit...rest looks good

File: core-common/src/main/kotlin/com/twitter/rules/core/util/Composables.kt (hunk 1 above)
Comment (PaulWoitaschek) [reply core-common/src/main/kotlin/com/twitter/rules/core/util/Composables.kt:53]: I copied the doc style from the other list. Personally I would not have used any docs here at all. 
Feel free to edit/ remove.

Comment (kenyee) [reply core-common/src/main/kotlin/com/twitter/rules/core/util/Composables.kt:53]: true...matches other comment 😄

**Review by kenyee — APPROVED** [review]

**Comment by kenyee** [comment]
> _****_

@PaulWoitaschek could you reply w/ a comment with the above text.  We actually have two CLA bots, weirdly enough...

**Comment by PaulWoitaschek** [comment]
>

**Comment by PaulWoitaschek** [comment]
I have read the CLA Document and I hereby sign the CLA

File: core-common/src/main/kotlin/com/twitter/rules/core/util/Composables.kt [hunk 3]
```diff
@@ -11,7 +12,27 @@ import org.jetbrains.kotlin.psi.KtProperty
 import org.jetbrains.kotlin.psi.psiUtil.referenceExpression
 
 val KtFunction.emitsContent: Boolean
-    get() = if (isComposable) findChildrenByClass<KtCallExpression>().any { it.emitsContent } else false
+    get() {
+        return if (isComposable) {
+            sequence {
+                suspend fun SequenceScope<KtCallExpression>.scan(current: PsiElement) {
```
Comment (mrmans0n) [inline core-common/src/main/kotlin/com/twitter/rules/core/util/Composables.kt:18]: can this be made tailrec? if not, then using a queue to make it iterative?

File: core-common/src/main/kotlin/com/twitter/rules/core/util/PsiElements.kt [hunk 4]
```diff
@@ -5,28 +5,27 @@ package com.twitter.rules.core.util
...
+                yield(current)
             }
             queue.addAll(current.children)
         }
     }
 
 inline fun <reified T : PsiElement> PsiElement.findDirectFirstChildByClass(): T? {
```
Comment (mrmans0n) [inline core-common/src/main/kotlin/com/twitter/rules/core/util/PsiElements.kt:24]: will this need to be reified then? (same for the others)

File: rules/detekt/src/test/kotlin/com/twitter/compose/rules/detekt/ComposeModifierMissingCheckTest.kt [hunk 5]
```diff
@@ -200,4 +200,45 @@ class ComposeModifierMissingCheckTest {
         val errors = rule.lint(code)
         assertThat(errors).isEmpty()
     }
+
+    @Test
+    fun `Non content emitting root composables are ignored`() {
```
Comment (mrmans0n) [inline rules/detekt/src/test/kotlin/com/twitter/compose/rules/detekt/ComposeModifierMissingCheckTest.kt:205]:
```suggestion
    fun `non content emitting root composables are ignored`() {
```

File: rules/detekt/src/test/kotlin/com/twitter/compose/rules/detekt/ComposeModifierMissingCheckTest.kt [hunk 6]
```diff
@@ -200,4 +200,45 @@ class ComposeModifierMissingCheckTest {
...
+                  )
+                }
+            """.trimIndent()
+
+        val errors = rule.lint(code)
+        assertThat(errors).isEmpty()
+    }
+
+    @Test
+    fun `Non content emitter with content emitter not ignored`() {
```
Comment (mrmans0n) [inline rules/detekt/src/test/kotlin/com/twitter/compose/rules/detekt/ComposeModifierMissingCheckTest.kt:224]:
```suggestion
    fun `non content emitter with content emitter not ignored`() {
```

File: rules/ktlint/src/test/kotlin/com/twitter/compose/rules/ktlint/ComposeModifierMissingCheckTest.kt [hunk 7]
```diff
@@ -214,4 +214,48 @@ class ComposeModifierMissingCheckTest {
 
         modifierRuleAssertThat(code).hasNoLintViolations()
     }
+
+    @Test
+    fun `Non content emitting root composables are ignored`() {
```
Comment (mrmans0n) [inline rules/ktlint/src/test/kotlin/com/twitter/compose/rules/ktlint/ComposeModifierMissingCheckTest.kt:219]:
```suggestion
    fun `non content emitting root composables are ignored`() {
```

File: rules/ktlint/src/test/kotlin/com/twitter/compose/rules/ktlint/ComposeModifierMissingCheckTest.kt [hunk 8]
```diff
@@ -214,4 +214,48 @@ class ComposeModifierMissingCheckTest {
...
+                    text = { Text(text = "Body") },
+                  )
+                }
+            """.trimIndent()
+
+        modifierRuleAssertThat(code).hasNoLintViolations()
+    }
+
+    @Test
+    fun `Non content emitter with content emitter not ignored`() {
```
Comment (mrmans0n) [inline rules/ktlint/src/test/kotlin/com/twitter/compose/rules/ktlint/ComposeModifierMissingCheckTest.kt:237]:
```suggestion
    fun `non content emitter with content emitter not ignored`() {
```

**Comment by mrmans0n** [comment]
Looks very nice, left a couple of comments, happy to re-review later

File: core-common/src/main/kotlin/com/twitter/rules/core/util/Composables.kt (hunk 3 above)
Comment (PaulWoitaschek) [reply core-common/src/main/kotlin/com/twitter/rules/core/util/Composables.kt:18]: Why would that be necessary? This runs on user written code and I don't see where it could produce a stack overflow.

Comment (mrmans0n) [reply core-common/src/main/kotlin/com/twitter/rules/core/util/Composables.kt:18]: Twitter for Android has several million LOC, and thousands of modules. It is the main target for us to run these rules. We've seen that not being conservative with memory causes heap to overflow our CI in the past, so any savings we can do here are worthwhile for us.

Comment (PaulWoitaschek) [reply core-common/src/main/kotlin/com/twitter/rules/core/util/Composables.kt:18]: Sure, but ktlint runs only on a single file. So even if you had very bad code standards and one function referencing 100 composables, that still would be premature optimization.

Comment (mrmans0n) [reply core-common/src/main/kotlin/com/twitter/rules/core/util/Composables.kt:18]: If you count that it is filtering by KtCallExpressions (so not only constrained to Composables), from experience (e.g. very, very similar code to this that had to be changed, and it was targeting individual files too) this can be problematic, even if it sounds like premature optimization. Some of these files are insanely big, and we don't have the numbers now after last Friday to address the necessary refactors anymore.

Comment (PaulWoitaschek) [reply core-common/src/main/kotlin/com/twitter/rules/core/util/Composables.kt]: All righty, even though I think it's premature optimization, here comes the tailrec magic 🧙‍♀️
