### PR TITLE
Don't publish shadowRuntimeElements variant unless it's an uber jar publication

### LINKED ISSUE #71: Cannot choose between the following variants (runtimeElements, shadowRuntimeElements)
**Describe the bug**

Since library version 0.0.10, we're facing an error when running detekt through Gradle:

```
> Could not resolve all files for configuration ':detektPlugins'.
   > Could not resolve com.twitter.compose.rules:detekt:0.0.11.
     Required by:
         project :
      > Cannot choose between the following variants of com.twitter.compose.rules:detekt:0.0.11:
          - runtimeElements
          - shadowRuntimeElements
        All of them match the consumer attributes:
          - Variant 'runtimeElements' capability com.twitter.compose.rules:detekt:0.0.11:
              - Unmatched attributes:
                  - Provides org.gradle.category 'library' but the consumer didn't ask for it
                  - Provides org.gradle.dependency.bundling 'external' but the consumer didn't ask for it
                  - Provides org.gradle.jvm.environment 'standard-jvm' but the consumer didn't ask for it
                  - Provides org.gradle.jvm.version '11' but the consumer didn't ask for it
                  - Provides org.gradle.libraryelements 'jar' but the consumer didn't ask for it
                  - Provides org.gradle.status 'release' but the consumer didn't ask for it
                  - Provides org.gradle.usage 'java-runtime' but the consumer didn't ask for it
                  - Provides org.jetbrains.kotlin.platform.type 'jvm' but the consumer didn't ask for it
          - Variant 'shadowRuntimeElements' capability com.twitter.compose.rules:detekt:0.0.11:
              - Unmatched attributes:
                  - Provides org.gradle.category 'library' but the consumer didn't ask for it
                  - Provides org.gradle.dependency.bundling 'shadowed' but the consumer didn't ask for it
                  - Provides org.gradle.libraryelements 'jar' but the consumer didn't ask for it
                  - Provides org.gradle.status 'release' but the consumer didn't ask for it
                  - Provides org.gradle.usage 'java-runtime' but the consumer didn't ask for it

```

It seems like this was introduced with `shadowJar`. I found related issues in the ktlint (https://github.com/pinterest/ktlint/issues/1114) and detekt (https://github.com/detekt/detekt/issues/3743, https://github.com/detekt/detekt/issues/3969, https://github.com/detekt/detekt/pull/3738) repositories. I also found a temporary workaround there:

```groovy
configurations.named("detektPlugins").configure { configuration ->
  configuration.attributes.attribute(
          Bundling.BUNDLING_ATTRIBUTE,
          objects.named(Bundling, Bundling.EXTERNAL)
  )
}
```

The detekt team solved it by not publishing the shadowRuntimeElements variant of detekt-cli anymore (https://github.com/detekt/detekt/pull/3747).

**To Reproduce**
1. use version 0.0.10/0.0.11
2. run `./gradlew detekt`
3. see error

### PR DESCRIPTION
**Pull request by mrmans0n**
Publishing `shadowRuntimeElements` variant can cause problems, so we will only be doing it when passing -PuberJar param to gradle. We'll disable this variant by default, and just enable it in CI in the update-release workflow.

Tested in:

- [x] ktlint-cli
- [x] detekt-cli
- [x] kotlinter
- [ ] detekt gradle

Will test the latter when I have a minute.

Fixes #71.

### CODE REVIEW

File: rules/detekt/src/main/kotlin/com/twitter/compose/rules/detekt/ComposeModifierWithoutDefaultCheck.kt [hunk 1]
```diff
@@ -14,8 +14,6 @@ class ComposeModifierWithoutDefaultCheck(config: Config) :
     TwitterDetektRule(config),
     ComposeKtVisitor by ComposeModifierWithoutDefault() {
 
-    override val autoCorrect: Boolean = true
```
Comment (digitalbuddha) [inline rules/detekt/src/main/kotlin/com/twitter/compose/rules/detekt/ComposeModifierWithoutDefaultCheck.kt:17]: Why this removed?

**Review by digitalbuddha — APPROVED** [review]

File: rules/detekt/src/main/kotlin/com/twitter/compose/rules/detekt/ComposeModifierWithoutDefaultCheck.kt (hunk 1 above)
Comment (mrmans0n) [reply rules/detekt/src/main/kotlin/com/twitter/compose/rules/detekt/ComposeModifierWithoutDefaultCheck.kt:17]: It was a bug that it was there, it causes a crash with detekt when triggered (e.g. from the cli).

**Comment by mrmans0n** [comment]
@digitalbuddha don't want to merge this just yet, I need to test it with kotlinter / detekt gradle still.

File: rules/detekt/src/test/kotlin/com/twitter/compose/rules/detekt/ComposeModifierWithoutDefaultCheckTest.kt [hunk 2]
```diff
@@ -27,7 +27,7 @@ class ComposeModifierWithoutDefaultCheckTest {
         val errors = rule.lint(composableCode)
         assertThat(errors).hasSourceLocations(
             SourceLocation(2, 15),
-            SourceLocation(4, 57)
+            SourceLocation(4, 46)
```
Comment (mrmans0n) [inline rules/detekt/src/test/kotlin/com/twitter/compose/rules/detekt/ComposeModifierWithoutDefaultCheckTest.kt:30]: dunno why this was 57 before?? just looked at the code it points, and 46 points at the `modifier2` name which is what we wanted?

**Comment by digitalbuddha** [comment]
Sg you'll have the +1 whenever it is ready.
